osx_image: xcode10
language: objective-c
cache:
  - bundler
  - cocoapods
addons:
  homebrew:
    update: true
    brewfile: true
branches:
  only:
    - develop
    - master
notifications:
  email: false
before_install:
  - gem install bundler && bundle install
install: bundle exec pod install --repo-update --silent
script: bundle exec fastlane tests
after_success: bundle exec fastlane ci_framework_deploy
